#!/usr/bin/python3
import sys
from collections import Counter
result = 0
for line in sys.stdin:
    words = line.lower().split()
    for word in words:
        if word.isalpha():
            ch,cnt = Counter(word).most_common(1)[0]
            result += cnt
print(result)
